
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Web;
using System.ComponentModel;
namespace BookStoreApiV2.Models
{

using System;
    using System.Collections.Generic;
    
    

    public partial class Category
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Category()
    {

        this.Books = new HashSet<Book>();

    }


    public int cId { get; set; }

    public string cName { get; set; }

    public string cDescription { get; set; }
    [DisplayName("Upload Image")]
    public string cImage { get; set; }

    public HttpPostedFileBase ImageFile { get; set; }

    public string cStatus { get; set; }

    public int cPosition { get; set; }

    public Nullable<System.DateTime> cCreatedAt { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Book> Books { get; set; }

}

}
