//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreApiV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int lId { get; set; }
        public Nullable<int> uId { get; set; }
        public string lLogType { get; set; }
        public string lUserType { get; set; }
        public Nullable<System.DateTime> lDateAndTime { get; set; }
    
        public virtual User User { get; set; }
    }
}
