
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BookStoreApiV2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class LoginCredential
{

    public string uMailId { get; set; }

    public string uPassword { get; set; }

    public int uId { get; set; }

    public string uRole { get; set; }

}

}
