//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreApiV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int ordrId { get; set; }
        public Nullable<int> oId { get; set; }
        public Nullable<int> uId { get; set; }
        public Nullable<int> bId { get; set; }
        public string bISBN { get; set; }
        public double bPrice { get; set; }
        public int bQuantity { get; set; }
        public double oTotalPrice { get; set; }
        public string oShippingAddress { get; set; }
        public string oBillingAddress { get; set; }
        public string oPaymentMode { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Order Order { get; set; }
        public virtual User User { get; set; }
    }
}
