//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreApiV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAddress
    {
        public int id { get; set; }
        public Nullable<int> uId { get; set; }
        public string uAddressLineOne { get; set; }
        public string uAddressLineTwo { get; set; }
        public string uLandMark { get; set; }
        public string uCity { get; set; }
        public string uState { get; set; }
        public string uCountry { get; set; }
        public string uPincode { get; set; }
    
        public virtual User User { get; set; }
    }
}
